[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F103VETx with your chip as listed in `probe-rs chip list`
runner="probe-rs run --chip STM32F103VETx"
linker="flip-link"

[build]
target="thumbv7m-none-eabi"
